### PR TITLE
adding file upload data to values in multipart body

### PR DESCRIPTION
**Pull request by sisoje**

### CODE REVIEW

**Review by Gorshtak — APPROVED** [review]

**Comment by BorntraegerMarc** [comment]
@sisoje Shouldn't we create a PR to the official project so the community can benefit from these changes?

**Comment by sisoje** [comment]
> @sisoje Shouldn't we create a PR to the official project so the community can benefit from these changes?

i don't think this particular change is beneficial to the community. it looks more like a special case just for komed, and we might need to even extend it further, right @Gorshtak ?

**Comment by BorntraegerMarc** [comment]
@sisoje as I understood the PR it's to enhance the file upload method so not only a file can be uploaded but additionally other data can be sent with the request. Is that correct?

If that is so then I think the community can benefit greatly from the feature 🙂

**Comment by sisoje** [comment]
@BorntraegerMarc i managed to add two more pr-s

**Pull request merged**
